CREATE TABLE members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login_id VARCHAR(20) COLLATE "C" NOT NULL,
    password VARCHAR(255) NOT NULL,
    family_name VARCHAR(12) NOT NULL,
    given_name VARCHAR(12) NOT NULL,
    nickname VARCHAR(12) COLLATE "C" NOT NULL
);

CREATE UNIQUE INDEX members_login_id_lower_unique ON members (lower(login_id));
CREATE UNIQUE INDEX members_nickname_lower_unique ON members (lower(nickname));
